### PR TITLE
Fix some bugs about theme

### PR DESCRIPTION
**Pull request by yzyray**
1.Fix wrong stone shadow size when drawing selected theme,currently it's always default theme's stone shadow size.
2.Fix out of index exception when delete last row of blunder node threshold and color
3.Fix when changed blunder node color and save,it's not saved in theme file or config file

### CODE REVIEW

**Comment by hope366** [comment]
#801 is also a PR about blunder colors and themes. How is this PR (#850) compared to #801?

**Comment by kaorahi** [comment]
797bb7f5 and 9194cee7 in #801 may be smarter fixes for 2 and 3?

@yzyray, could you split your fixes and make a separated PR for 1?

**Comment by yzyray** [comment]
> #801 is also a PR about blunder colors and themes. How is this PR (#850) compared to #801?
#801 is better
> @yzyray, could you split your fixes and make a separated PR for 1?
ok,I'll pr for 1 and  close this

**Comment by kaorahi** [comment]
thx!

**Pull request closed without merging**
